apiVersion: v1
kind: ServiceAccount
metadata:
  name: portal
  namespace: ceramics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ceramic-manager
  namespace: ceramics
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["traefik.io"]
    resources: ["ingressroutes"]
    resourceNames: ["portal"]
    verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: portal-ceramic-manager
  namespace: ceramics
subjects:
  - kind: ServiceAccount
    name: portal
    namespace: ceramics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ceramic-manager
