apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - sealed-secret-oauth2-proxy.yaml
  - job-keycloak-setup.yaml
  - oauth2-proxy.yaml
  - middleware-oauth2-proxy.yaml
patches:
  - target:
      kind: Deployment
      name: pottery
    path: patch-deployment.yaml
  - target:
      kind: IngressRoute
      name: pottery
    path: patch-ingressroute.yaml
