apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pottery
  namespace: ceramics
spec:
  routes:
    - match: HostRegexp(`^(ceramics|[a-z]+-[a-z]+-(clay|bat|vent))\.platform\.visari\.org$`)
      kind: Rule
      middlewares:
        - name: studio-auth
      services:
        - name: pottery
          port: 80
    - match: HostRegexp(`^[a-z]+-[a-z]+-glaze\.platform\.visari\.org$`)
      kind: Rule
      services:
        - name: pottery
          port: 80
  tls:
    certResolver: letsencrypt
