apiVersion: apps/v1
kind: Deployment
metadata:
  name: pottery
  namespace: ceramics
spec:
  template:
    spec:
      containers:
        - name: pottery
          env:
            - name: POTTERY_ORIGIN
              value: https://ceramics.myeatmovesave.visari.org
            - name: CERAMIC_DOMAIN
              value: myeatmovesave.visari.org
