---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy
  namespace: ceramics
spec:
  encryptedData:
    client-secret: AgCxyj5l4syHDTpk3o6T1dKTC5GXlobaaEemFawmkfiw0sOpAtkrQld1RtJdEpCGRH4Qti66SbCi60Okl1OTzS83qLpxGiOtOpPNhg839Ys1Srq4GABumU3b8ZVtUvGlCNLH+58U6PDPDaXukCTWXE5Zkz4QjhtJK0B0RUtrrHbhpALld7udzY+FYsLOzWC7xlZMRNrUgBdk/d7OEDdSO5n4+9aYJt0nWxk+R0OxfhzWiwQxsy5skyclUFcTzO1ICsmaPt/33QkjmccohwKsb3+5I/IuMLnvtPfGmBMFiAiDppIIwtN4HtteGQZInaRET2gPa5B3dSXTpUrYw5X38mH/tfRGmOxrY1en9HeEVtv3IC5+MhrX4KeViq9Ds/T2QLgvBKcl/S/pzagMw1dZt9OYaxy2fScc/T5yR5gmdP34tGYJBq58134/tFla+lMygcm4jpFIFBpy9Byf4p0ye7EH62PpKTH3hqDookl+FWwNjFdSg8fmGfU5KJvfA+N+O4+gGdwqBsM1v2u5uJfcCvfFkP9EjOjOz+F6Eg4TTkmldVpg8b+b2+G2ccdbrEYZ5jlv30PICSb3L3THVTI/wtWAjF88fpnA46k3JmxUTYj+RiEG38Vz3Tc89x+dk+zTvlGE+nH1GVtwCZU0CMt0pwzF9Nsa62JZYRIsMk8/dD6IHLpPrsOzDZCm3AEwu8+Q/Y0KtK2rLi78n9HTW5EieZQ1IcE4KN1ClyIheWaXsDCgLuEsYXCOC6CLUSOBkTiPG7Z3fSEPn+kDwRt3nuwEMB7c
    cookie-secret: AgCF1mS/lcOR3yDN7MAuM0W1as8KSGaZdp21KfRndTAJd5zZfaQjEBpX+hETsFMFNHx/70MG4OAsw7P4GqMJfGO4HrbhLHj0me7nh7lZvhuronzVCRIEnd//zhCFKXaxjnIakqR989Xsw9zytU76PubswhzZeVRr8DcoGywQqwfQE+j7aVjaekl6QLIo6kLIF5RnLJpJFfkSJrM+TlXZbIeLPm/G+eR/UdNPpz6tS/diz9z0w2Kmm+7M47sSrlHIOvhpSH3AJyEV0jnl55x8esrf8/lQx5UarVOAJAX6zy+ghU1Sm3LfAdJDc7h53K59zIjQ/T/mkN65srEbaaNzDk7/AOFAorm34ZjUJZVhah5+cEQ+gAnCXa1UqJcnJMRjUbyBhHhY/4Kr3KBHG0Kdx1Q+CpHDKcKQVMbg9d/+7qRelNQsM8x03nokEufa4Oqh9sRvlQKU99pnvj8VhxyLJeNpPSzV5Wj/+GRceEvoyH0q8t+8ZYgDYRtYM4rwpHUMps/rc3Rdm7r2boHW9Xn4HR6+NAGa0Rh4/DRu9QK4qoaUFGxCqEf+IJoaol/StLA+48BVEXGlTJRrXM4eFLV7OZUNvWTlrO3KyrhkUz40HLYslaXQFnzy4VS+Gk3ehccxX6m876oEzd/36anu5f7BxsSJY4Hd8jGysa4uv3A9sBRswt4UQwKP+3d6/dqEyxCiPVqi0OS3lrGxLe2fXst09ccCH5uJ7gY/3BdP9NLpCxDxIQ==
  template:
    metadata:
      name: oauth2-proxy
      namespace: ceramics
