---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: studio-auth-users
  namespace: ceramics
spec:
  encryptedData:
    users: AgCsuOf10PDRr5TJ7sSMHjvrGJ+9hFHoUuKacAVGunn8sKrth7XLmVv2DJ//P3QE5dBT/ouBsurM5OoxbEM9YTE3q4tT/WdXSt+aF0zSrRXD8jSVyBkYfxrV6wX/pWBXOJkggQcg4L7Pru02bTEpvviwVqHp/JBLRuYuxS0fvXlgm/TxA/TdUwMIgB8mi6FeujAC5A1F7J2kRly/Mb5fl+zlAQ3VK6Y3Uw3Oi+DEG+IKUVSdHHBt70j481bhddrrSbOlOlef+5mcxjHW0HFvI0xbFE5AUx36M3NsifbkvI/NA5zsSWxWq+rPMr8VFWH+eikuKKJJJ8cAZKRgOsFkS0Ouw4vwje5wjUXOdzE9TLcA2BtCZo9m0haGPj5SlbETqjlnaDiFD89nYVj8Sewdzl4gaxFG8rUXLkFgTWlbXM0IHyE38mofEdgfkqn3chp6SHlDRl3iibddB0BU5bbXKJwAHc+0HFA8xHiiDH/Jn+B0T61mxCFboSzrjKj/yt/iThUUM7enPkl6JZXNP5+aoC9cvm//+YDtDmbajZY2G5D7YzXrvXb4BvwrKrtUpuIpuZ16NHf9SoSD5czGC48jkAxis0WOBQSy1/qu9kABUm4Q2yRM1uucen9x5BwwoET1iyo+nCUwxV0SPKuwppKIDpQsgGfZie2UUsA0aSr1i2CWnBNcPolZsGsVJEojmnFRsWTPsmd6ghBCiTQcINGM0PVA2ovmJjeTNL9Mb+NWaoJcnxdOw/gcQF3OW2RjLxhYIViyVVM3F5g1EkJWct5pedgfrxxO1Q==
  template:
    metadata:
      name: studio-auth-users
      namespace: ceramics
