apiVersion: apps/v1
kind: Deployment
metadata:
  name: pottery
  namespace: ceramics
spec:
  template:
    spec:
      containers:
        - name: pottery
          env:
            - name: POTTERY_ORIGIN
              value: https://ceramics.141.142.218.86.nip.io
            - name: CERAMIC_DOMAIN
              value: 141.142.218.86.nip.io
